nginx:
  build: "nginx"
  ports:
    - "80:80"
    - "443:443"
  links:
    - goshare:goshare
  volumes:
    - ~/goshare-website/build:/usr/share/nginx/html
    - ~/cert:/etc/nginx/cert
goshare:
  build: "../../"
  ports:
    - "8080"
  environment:
    DSN: "root:123@tcp(db)/goshare?charset=utf8mb4&parseTime=true"
    SAVEPATH: "redis:6379,10,60"
    MONGODBURI: "mongodb://mongo:27017"
  links:
    - db:db
    - redis:redis
    - mongo:mongo
db:
  image: mysql
  ports:
    - "3306"
  environment:
    - MYSQL_ROOT_PASSWORD=123
redis:
  image: redis
  ports:
    - "6379"
mongo:
  image: mongo
  ports:
    - "27017"